environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "Boost/1.65.1"
    CONAN_SUBJECT: "bincrafters"
    CONAN_CHANNEL: "ci"
    CONAN_REPO: "public-conan"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools

build_script:
  - conan create %CONAN_SUBJECT%/%CONAN_CHANNEL%
  
deploy_script:
  - set CONAN_REFERENCE_FULL=%CONAN_REFERENCE%@%CONAN_SUBJECT%/%CONAN_CHANNEL%
  - echo %CONAN_REFERENCE_FULL%
  - conan remote add %CONAN_SUBJECT% "https://api.bintray.com/conan/%CONAN_SUBJECT%/%CONAN_REPO%"
  - conan user -p %CONAN_KEY% --remote %CONAN_SUBJECT% %CONAN_USER%
  - conan upload --all --remote %CONAN_SUBJECT%  %CONAN_REFERENCE_FULL%